/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface KasumahOwnerConfigsInterface extends ethers.utils.Interface {
  functions: {
    "latest(address,uint256,string)": FunctionFragment;
    "set(address,uint256,string,bytes)": FunctionFragment;
    "snapshotSlice(address,uint256,string,uint256,uint256)": FunctionFragment;
    "valueAt(address,uint256,string,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "latest",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [string, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshotSlice",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "valueAt",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "latest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "snapshotSlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "valueAt", data: BytesLike): Result;

  events: {};
}

export class KasumahOwnerConfigs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: KasumahOwnerConfigsInterface;

  functions: {
    latest(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      overrides?: CallOverrides
    ): Promise<[string] & { value: string }>;

    set(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    snapshotSlice(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { blockNumbers: BigNumber[] }>;

    valueAt(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { value: string }>;
  };

  latest(
    erc1155Contract: string,
    tokenID: BigNumberish,
    key: string,
    overrides?: CallOverrides
  ): Promise<string>;

  set(
    erc1155Contract: string,
    tokenID: BigNumberish,
    key: string,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  snapshotSlice(
    erc1155Contract: string,
    tokenID: BigNumberish,
    key: string,
    start: BigNumberish,
    length: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  valueAt(
    erc1155Contract: string,
    tokenID: BigNumberish,
    key: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    latest(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      overrides?: CallOverrides
    ): Promise<string>;

    set(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    snapshotSlice(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    valueAt(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    latest(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    set(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    snapshotSlice(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    valueAt(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    latest(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    set(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    snapshotSlice(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    valueAt(
      erc1155Contract: string,
      tokenID: BigNumberish,
      key: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
